### ISSUE TITLE
[Bug] 국내 개인목록에서 검색을 하면 오류가 발생합니다.

### ISSUE THREAD

**Issue by hyelimchoi1223** [sarojaba/awesome-devblog#477]
국내 > 개인목록 에서 검색을 하면 아래와 같은 오류가 발생해서 제보드립니다.
```
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"FetchError: invalid json response body at https://awesome-devblog-backend-korean-people.vercel.app/api/korean/people?sort=name.asc&page=1&size=15&name=%EC%B5%9C%ED%98%9C%EB%A6%BC reason: Unexpected token A in JSON at position 0","trace":["Runtime.UnhandledPromiseRejection: FetchError: invalid json response body at https://awesome-devblog-backend-korean-people.vercel.app/api/korean/people?sort=name.asc&page=1&size=15&name=%EC%B5%9C%ED%98%9C%EB%A6%BC reason: Unexpected token A in JSON at position 0","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:314:20)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
```

**Comment by sarojaba** [comment]
API 서버로 Vercel의 서비스를 이용하고 있는데, 가끔씩 에러가 나는 경우가 있네요.

**Comment by sarojaba** [comment]
API 서버를 바꾸었습니다.
잘 되는지 확인 부탁드립니다.

**Comment by hyelimchoi1223** [comment]
검색 잘 되는 것 확인했습니다~~ 덕분에 좋은 서비스 이용하고 있습니다!! 감사합니다😄
